name: .NET CI with UI & k6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # ---- Unit & BDD tests ----
      - name: Run Unit Tests
        run: dotnet test BPCalculator.UnitTests/BPCalculator.UnitTests.csproj --no-build --configuration Release

      - name: Run BDD Tests
        run: dotnet test BPCalculator.BddTests/BPCalculator.BddTests.csproj --no-build --configuration Release


  ui-tests:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # 1) Build Playwright tests so the playwright.ps1 script exists
      - name: Build Playwright tests (Debug)
        run: dotnet build BPCalculator.PlaywrightTests/BPCalculator.PlaywrightTests.csproj -c Debug

      # 2) Install Playwright browsers on the GitHub runner
      - name: Install Playwright browsers
        run: pwsh BPCalculator.PlaywrightTests/bin/Debug/net8.0/playwright.ps1 install

      # 3) Run Playwright tests
      - name: Playwright UI Tests
        run: dotnet test BPCalculator.PlaywrightTests/BPCalculator.PlaywrightTests.csproj -c Debug

      # 4) Run Selenium tests
      - name: Selenium UI Tests
        run: dotnet test BPCalculator.SeleniumTests/BPCalculator.SeleniumTests.csproj --configuration Release


  k6-performance:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Start the web app so k6 can hit http://localhost:5000
      - name: Start Web App
        run: |
          dotnet run --project BPCalculator/BPCalculator.csproj --urls http://localhost:5000 &
          sleep 10

      - name: Run k6 load test
        run: |
          docker run --rm -i grafana/k6 run - < ./k6/bp_performance_test.js
