name: .NET CI with UI & k6

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ===========================
  # 1) Build + Unit + BDD tests
  # ===========================
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test BPCalculator.UnitTests/BPCalculator.UnitTests.csproj --no-build --configuration Release

      - name: Run BDD Tests
        run: dotnet test BPCalculator.BddTests/BPCalculator.BddTests.csproj --no-build --configuration Release

  # ===========================
  # 2) UI tests (Playwright + Selenium)
  # ===========================
  ui-tests:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Build Playwright test project so playwright.ps1 is generated
      - name: Build Playwright test project
        run: dotnet build BPCalculator.PlaywrightTests/BPCalculator.PlaywrightTests.csproj --configuration Release

      # Install Playwright browsers on the runner
      - name: Install Playwright browsers
        run: pwsh BPCalculator.PlaywrightTests/bin/Release/net8.0/playwright.ps1 install

      - name: Playwright UI Tests
        run: dotnet test BPCalculator.PlaywrightTests/BPCalculator.PlaywrightTests.csproj --no-build --configuration Release

      - name: Selenium UI Tests
        run: dotnet test BPCalculator.SeleniumTests/BPCalculator.SeleniumTests.csproj --configuration Release

  # ===========================
  # 3) k6 performance tests
  # ===========================
  k6-performance:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      # Start the Web API on the runner so k6 can hit http://localhost:5000
      - name: Start Web App
        run: |
          dotnet run --project BPCalculator/BPCalculator.csproj --configuration Release --urls http://localhost:5000 &
          sleep 10  # give the app time to start

      - name: Run k6 load test
        run: |
          docker run --rm --network host -i grafana/k6 run - < ./k6/bp_performance_test.js
