name: .NET CI with UI & k6

on:
  push:

jobs:
  # -------------------- BUILD + BASIC TESTS --------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore BPCalculator.sln

      - name: Build
        run: dotnet build BPCalculator.sln --configuration Release --no-restore

      # If you have these projects, keep these lines; otherwise you can remove them.
      - name: Run Unit Tests
        run: dotnet test BPCalculator.UnitTests/BPCalculator.UnitTests.csproj --no-build --configuration Release

      - name: Run BDD Tests
        run: dotnet test BPCalculator.BddTests/BPCalculator.BddTests.csproj --no-build --configuration Release

  # -------------------- PLAYWRIGHT UI TESTS --------------------
  ui-tests:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore Playwright project
        run: dotnet restore BPCalculator.PlaywrightTests/BPCalculator.PlaywrightTests.csproj

      - name: Build Playwright tests
        run: dotnet build BPCalculator.PlaywrightTests/BPCalculator.PlaywrightTests.csproj \
             --configuration Release --no-restore

      # 🔴 This line does exactly what the error message tells you to do
      - name: Install Playwright browsers
        run: pwsh BPCalculator.PlaywrightTests/bin/Release/net8.0/playwright.ps1 install --with-deps

      - name: Playwright UI Tests
        run: dotnet test BPCalculator.PlaywrightTests/BPCalculator.PlaywrightTests.csproj \
             --configuration Release --no-build

      # Optional: Selenium tests, if you have this project
      - name: Selenium UI Tests
        run: dotnet test BPCalculator.SeleniumTests/BPCalculator.SeleniumTests.csproj \
             --configuration Release --no-build

  # -------------------- k6 PERFORMANCE TESTS --------------------
  k6-performance:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run k6 load test
        run: |
          docker run --rm -i grafana/k6 run - < ./k6/bp_performance_test.js
