name: SonarCloud analysis (.NET)

on:
  push:
    branches:
      - main           # run when main is updated
  pull_request:
    branches:
      - main           # run on PRs targeting main
  workflow_dispatch:    # allow manual runs from the Actions tab

jobs:
  sonar-analysis:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # SonarCloud prefers full history for blame info

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"

      # ---- SonarCloud begin ----
      - name: SonarCloud - Begin analysis
        run: >
          dotnet-sonarscanner begin
          /k:"$SONAR_PROJECT_KEY"
          /o:"$SONAR_ORG"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.token="$SONAR_TOKEN"
          /d:sonar.cs.opencover.reportsPaths="**/TestResults/coverage.opencover.xml"
      # --------------------------

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      # Only UnitTests for coverage (no Selenium / Playwright here)
      - name: Test UnitTests with coverage
        run: >
          dotnet test ./BPCalculator.UnitTests/BPCalculator.UnitTests.csproj
          --no-build --configuration Release
          /p:CollectCoverage=true
          /p:CoverletOutput=./TestResults/coverage
          /p:CoverletOutputFormat=opencover

      # ---- SonarCloud end ----
      - name: SonarCloud - End analysis
        run: dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
      # ------------------------
