name: .NET CI with SonarCloud

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # SonarCloud prefers full history

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # ---- SonarCloud begin ----
      - name: SonarCloud - Begin analysis
        run: >
          dotnet-sonarscanner begin
          /k:"$SONAR_PROJECT_KEY"
          /o:"$SONAR_ORG"
          /d:sonar.host.url="https://sonarcloud.io"
          /d:sonar.token="$SONAR_TOKEN"
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
      # --------------------------

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test UnitTests with coverage
        run: >
          dotnet test ./BPCalculator.UnitTests/BPCalculator.UnitTests.csproj
          --no-build --configuration Release
          /p:CollectCoverage=true
          /p:CoverletOutput=./TestResults/
          /p:CoverletOutputFormat=opencover

      # ---- SonarCloud end ----
      - name: SonarCloud - End analysis
        run: dotnet-sonarscanner end /d:sonar.token="$SONAR_TOKEN"
      # ------------------------
